"""Update review_type column in past_trips table to Enum

Revision ID: 2e5cc10f3e3e
Revises: 4d5401e76125
Create Date: 2025-02-27 20:34:06.554453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5cc10f3e3e'
down_revision = '4d5401e76125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trips', schema=None) as batch_op:
        batch_op.alter_column('review_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('private', 'public', name='review_type_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trips', schema=None) as batch_op:
        batch_op.alter_column('review_type',
               existing_type=sa.Enum('private', 'public', name='review_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
