"""Add review_type to User model

Revision ID: 3d588e1955f4
Revises: 8e8f738c6957
Create Date: 2025-02-26 20:35:52.546294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d588e1955f4'
down_revision = '8e8f738c6957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('review_type')

    # ### end Alembic commands ###
