"""Remove review and review_type columns from User table

Revision ID: 45295f50da88
Revises: 75f3adce98c5
Create Date: 2025-02-27 20:21:06.211192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45295f50da88'
down_revision = '75f3adce98c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('review')
        batch_op.drop_column('review_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('review', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
