"""Add points to Trip and Product

Revision ID: 4631143e5d1e
Revises: 
Create Date: 2025-01-25 09:13:11.628266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4631143e5d1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('points', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('trip', sa.Column('points', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'points')
    op.drop_column('trip', 'points')