"""Add review and review_type columns to past_trips table

Revision ID: 4d5401e76125
Revises: 45295f50da88
Create Date: 2025-02-27 20:26:43.783035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5401e76125'
down_revision = '45295f50da88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_trips', schema=None) as batch_op:
        batch_op.drop_column('review_type')
        batch_op.drop_column('review')

    # ### end Alembic commands ###
