"""Add status column to Trip model

Revision ID: 6bbe8cd13a73
Revises: 2e5cc10f3e3e
Create Date: 2025-03-19 22:39:29.427319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe8cd13a73'
down_revision = '2e5cc10f3e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False,server_default='upcoming'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
