"""Remove status column from Trip table

Revision ID: 780f410de5fe
Revises: d4e30e5c4845
Create Date: 2025-02-26 18:26:11.550495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780f410de5fe'
down_revision = 'd4e30e5c4845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
