"""Add review column to User table

Revision ID: 8e8f738c6957
Revises: 4bdf3d69c4a5
Create Date: 2025-02-26 19:00:05.010938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8f738c6957'
down_revision = '4bdf3d69c4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('review')

    # ### end Alembic commands ###
