"""Added wishlist, booked, and past trip relationships

Revision ID: 94099dbbe346
Revises: df3fcb8cec36
Create Date: 2025-02-24 21:20:03.904772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94099dbbe346'
down_revision = 'df3fcb8cec36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trips',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('trip_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    # ### end Alembic commands ###
