"""Add loyalty points and rating to user

Revision ID: df3fcb8cec36
Revises: 4631143e5d1e
Create Date: 2025-01-25 11:01:05.887637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3fcb8cec36'
down_revision = '4631143e5d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_rating', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('loyalty_rating')
        batch_op.drop_column('loyalty_points')

    # ### end Alembic commands ###
